services:
  - type: web
    name: pharmacy-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate &&
      gunicorn pharm.wsgi --log-file -
